name: sdui_server
description: SDUI Dart backend server
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  sdui_models:
    path: ../sdui_models

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.6
  shelf_test_handler: ^0.2.0
